name: "Build PHP FPM"
on:
  push:
    branches:
        - master
  workflow_dispatch:

jobs:
    main:
        name: "Build & Deploy"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DH_USERNAME }}
                password: ${{ secrets.DH_TOKEN }}

            - name: Build PHP7.4-FPM and push
              uses: docker/build-push-action@v2
              with:
                context: ./php/fpm/
                file: ./php/fpm/php74.dockerfile
                push: true
                tags: ${{ secrets.DH_USERNAME }}/php74-fpm:latest