name: "Build & Publish PHP"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-publish:
    name: php-${{ matrix.version }}-${{ matrix.type }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [ '74', '80', '81' ]
        type: [ 'fpm', 'worker' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          context: ./php/
          file: ./php/php${{ matrix.version }}-${{ matrix.type }}.dockerfile
          push: true
          tags: ${{ secrets.DH_USERNAME }}/php:${{ matrix.type }}-${{ matrix.version }}-latest
