# name/php:fpm-74-latest
# name/php:fpm-80-latest
# name/php:worker-74-latest
# name/php:worker-80-latest

name: "Build & Publish PHP"
on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    fpm:
        name: ${{ matrix.name }}-fpm
        runs-on: ubuntu-latest

        strategy:
            matrix:
                name: [ 'php74' ]
                include:
                    - name: php74
                      short_name: 74

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DH_USERNAME }}
                    password: ${{ secrets.DH_TOKEN }}

            # -   name: Get current date
            #     id: date
            #     run: echo "::set-output name=DATE::$(date +'%Y%m%d')"

            -   name: Build ${{ matrix.name }}-fpm and publish
                uses: docker/build-push-action@v2
                with:
                    context: ./php/fpm/
                    file: ./php/fpm/php${{ matrix.short_name }}.dockerfile
                    push: true
                    tags: ${{ secrets.DH_USERNAME }}/php:fpm-${{ matrix.short_name }}-latest
                    # tags:
                    #     - ${{ secrets.DH_USERNAME }}/php:fpm-${{ matrix.name }}-${{ steps.date.outputs.DATE }}
                    #     - ${{ secrets.DH_USERNAME }}/php:fpm-${{ matrix.name }}-latest
    worker:
        name: ${{ matrix.name }}-worker
        runs-on: ubuntu-latest

        strategy:
            matrix:
                name: [ 'php74' ]
                include:
                    - name: php74
                      short_name: 74

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DH_USERNAME }}
                    password: ${{ secrets.DH_TOKEN }}

            # -   name: Get current date
            #     id: date
            #     run: echo "::set-output name=DATE::$(date +'%Y%m%d')"

            -   name: Build ${{ matrix.name }}-worker and publish
                uses: docker/build-push-action@v2
                with:
                    context: ./php/worker/
                    file: ./php/worker/worker_${{ matrix.short_name }}.dockerfile
                    push: true
                    tags: ${{ secrets.DH_USERNAME }}/php:worker-${{ matrix.short_name }}-latest
                    # tags:
                    #     - ${{ secrets.DH_USERNAME }}/php:fpm-${{ matrix.name }}-${{ steps.date.outputs.DATE }}
                    #     - ${{ secrets.DH_USERNAME }}/php:fpm-${{ matrix.name }}-latest
